// Generated by CoffeeScript 1.2.1-pre
/*
@author Matt Crinklaw-Vogt
*/

define(["vendor/backbone", "./Templates", "./SlidePreviewPanel", "./OperatingTable", "common/EventEmitter", "css!./res/css/SlideEditor.css", "./button_bar/ButtonBarView", "ui/widgets/PictureGrabber", "vendor/keymaster"], function(Backbone, Templates, SlidePreviewPanel, OperatingTable, EventEmitter, empty, ButtonBarView, PictureGrabber, Keymaster) {
  return Backbone.View.extend({
    className: "slideEditor",
    initialize: function() {
      this.name = "Slide Editor";
      this.operatingTable = new OperatingTable();
      this.slidePreviewPanel = new SlidePreviewPanel({
        model: this.model
      });
      return this.model.on("change:activeSlide", this._activeSlideChanged, this);
    },
    show: function() {
      this.hidden = false;
      this.$el.removeClass("disp-none");
      Keymaster.setScope("slidePreviewPanel");
      if (this.hiddenActiveChange != null) {
        this.operatingTable.setModel(this.hiddenActiveChange);
        return this.hiddenActiveChange = null;
      }
    },
    cut: function() {
      var component;
      component = this[Keymaster.getScope()];
      if (component != null) component.cut();
      return true;
    },
    copy: function() {
      var component;
      component = this[Keymaster.getScope()];
      if (component != null) component.copy();
      return true;
    },
    paste: function() {
      var component;
      component = this[Keymaster.getScope()];
      if (component != null) component.paste();
      return true;
    },
    backgroundChanged: function(newBG) {
      var style, _i, _len, _ref, _results;
      _ref = newBG.styles;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        style = _ref[_i];
        _results.push(this.$operatingTable.css("background-image", style));
      }
      return _results;
    },
    hide: function() {
      this.hidden = true;
      return this.$el.addClass("disp-none");
    },
    _activeSlideChanged: function(model, newSlide) {
      if (!this.hidden) {
        return this.operatingTable.setModel(newSlide);
      } else {
        return this.hiddenActiveChange = newSlide;
      }
    },
    render: function() {
      var $items, $mainContent, pictureGrabber;
      this.$el.html(Templates.SlideEditor(this.model));
      this.$el.find(".dropdown-toggle").dropdown();
      $items = this.$el.find("a[title]");
      $items.tooltip({
        placement: 'bottom',
        delay: {
          show: 1000,
          hide: 100
        }
      }).click(function() {
        return $items.tooltip('hide');
      });
      $mainContent = this.$el.find(".mainContent");
      this.$slidePreviewPanel = this.slidePreviewPanel.render();
      this.$operatingTable = this.operatingTable.render();
      $mainContent.append(this.$slidePreviewPanel);
      $mainContent.append(this.$operatingTable);
      if (this._buttonBar != null) this._buttonBar.dispose();
      pictureGrabber = new PictureGrabber();
      this.$el.append(pictureGrabber.render());
      this._buttonBar = new ButtonBarView({
        el: this.$el.find(".buttonBar"),
        deck: this.model,
        pictureGrabber: pictureGrabber
      });
      this._buttonBar.render();
      return this.$el;
    },
    resized: function() {
      if (this.$slidePreviewPanel) {
        this.$slidePreviewPanel.css("height", window.innerHeight - 80);
        this.$operatingTable.css("height", window.innerHeight - 80);
        return this.$operatingTable.css("width", window.innerWidth - 150);
      }
    }
  });
});
