// Generated by CoffeeScript 1.2.1-pre
/*
@author Matt Crinklaw-Vogt
*/

define(["vendor/backbone", "./Templates", "css!./res/css/SlideSnapshot.css", "./raster/SlideDrawer"], function(Backbone, Templates, empty, SlideDrawer) {
  return Backbone.View.extend({
    className: "slideSnapshot",
    events: {
      "click": "clicked",
      "click .removeBtn": "removeClicked"
    },
    initialize: function() {
      this.model.on("change:active", this._activated, this);
      return this.model.on("dispose", this._modelDisposed, this);
    },
    clicked: function() {
      this.model.set("selected", true);
      return this.model.set("active", true);
    },
    removeClicked: function(e) {
      this.trigger("removeClicked", this);
      return e.stopPropagation();
    },
    remove: function() {
      this.slideDrawer.dispose();
      this.off();
      this.$el.data("jsView", null);
      return Backbone.View.prototype.remove.apply(this, arguments);
    },
    _activated: function(model, value) {
      if (value) {
        return this.$el.addClass("active");
      } else {
        return this.$el.removeClass("active");
      }
    },
    _modelDisposed: function() {
      this.model.off(null, null, this);
      return this.remove();
    },
    render: function() {
      var g2d;
      if (this.slideDrawer != null) this.slideDrawer.dispose();
      this.$el.html(Templates.SlideSnapshot(this.model.attributes));
      g2d = this.$el.find("canvas")[0].getContext("2d");
      this.slideDrawer = new SlideDrawer(this.model, g2d);
      this.slideDrawer.repaint();
      if (this.model.get("active")) this.$el.addClass("active");
      this.$el.data("jsView", this);
      return this.$el;
    }
  });
});
