// Generated by CoffeeScript 1.2.1-pre
/*
@author Matt Crinklaw-Vogt
*/

define(["vendor/backbone"], function(Backbone) {
  return Backbone.View.extend({
    initialize: function() {
      return this.name = "Transition Editor";
    }
  });
});
