// Generated by CoffeeScript 1.2.1-pre

define(["vendor/backbone"], function(Backbone) {
  var defaults;
  defaults = {
    template: function(model) {
      return this.label();
    }
  };
  return Backbone.View.extend({
    tagName: "button",
    className: "btn",
    events: function() {
      return {
        "click": "click"
      };
    },
    initialize: function() {
      _.defaults(this.options, defaults);
      this.template = this.options.template;
      return this._bind();
    },
    _bind: function() {
      return this.$el.bind("destroyed", this._dipose.bind(this));
    },
    click: function(e) {
      return this.trigger("click", e);
    },
    label: function() {
      var result;
      if (this.options.label != null) {
        result = this.options.label;
      } else if (this.options.field != null) {
        result = this.model.get(this.options.field);
      }
      if (this.options.formatter != null) result = this.options.formatter(result);
      return result;
    },
    dispose: function() {
      if (this.model != null) return this.model.off(null, null, this);
    },
    render: function() {
      return this.$el.html(this.template.call(this, this.model));
    }
  });
});
