// Generated by CoffeeScript 1.2.1-pre
/*
@author Tantaman
*/

define(["./Component"], function(Component) {
  return Component.extend({
    initialize: function() {
      return this.set("type", "ImageModel");
    },
    constructor: function ImageModel() {
			Component.prototype.constructor.apply(this, arguments);
		}
  });
});
