// Generated by CoffeeScript 1.3.3
/*
@author Tantaman
*/

define(["./Component"], function(Component) {
  return Component.extend({
    initialize: function() {
      this.set("type", "TextBox");
      if (!(this.get("text") != null)) {
        return this.set("text", "Text");
      }
    },
    textWithBreaks: function() {},
    constructor: function TextBox() {
			Component.prototype.constructor.apply(this, arguments);
		}
  });
});
