// Generated by CoffeeScript 1.2.1-pre
/*
@author Matt Crinklaw-Vogt
*/

define(["common/Throttler"], function(Throttler) {
  var SlideDrawer;
  return SlideDrawer = (function() {

    SlideDrawer.name = 'SlideDrawer';

    function SlideDrawer(model, g2d) {
      this.model = model;
      this.g2d = g2d;
      this.model.on("contentsChanged", this.repaint, this);
      this.size = {
        width: this.g2d.canvas.width,
        height: this.g2d.canvas.height
      };
      this.throttler = new Throttler(600, this);
      this.scale = this.size.width / slideConfig.size.width;
    }

    SlideDrawer.prototype.resized = function(newSize) {
      this.size = newSize;
      this.scale = this.size.width / slideConfig.size.width;
      return this.repaint();
    };

    SlideDrawer.prototype.repaint = function() {
      return this.throttler.submit(this.paint, {
        rejectionPolicy: "runLast"
      });
    };

    SlideDrawer.prototype.paint = function() {
      var components,
        _this = this;
      this.g2d.clearRect(0, 0, this.size.width, this.size.height);
      components = this.model.get("components");
      return components.forEach(function(component) {
        var type;
        type = component.get("type");
        _this.g2d.save();
        /*
        				# TODO: figure out correct translation to apply after transforms
        				skewX = component.get("skewX")
        				skewY = component.get("skewY")
        				transform = [1,0,0,1,0,0]
        				if skewX
        					transform[1] = skewX
        				if skewY
        					transform[2] = skewY
        				@g2d.transform.apply(@g2d, transform)
        
        				rotate = component.get("rotate")
        				if rotate
        					@g2d.rotate(rotate)
        */

        switch (type) {
          case "TextBox":
            _this.paintTextBox(component);
            break;
          case "ImageModel":
            _this.paintImage(component);
            break;
          case "Table":
            _this.paintTable(component);
        }
        return _this.g2d.restore();
      });
    };

    SlideDrawer.prototype.paintTextBox = function(textBox) {
      var bbox, txtWidth;
      this.g2d.fillStyle = "#" + textBox.get("color");
      this.g2d.font = textBox.get("size") * this.scale + "px " + textBox.get("family");
      txtWidth = this.g2d.measureText(textBox.get("text")).width * this.scale;
      bbox = {
        x: textBox.get("x") * this.scale,
        y: textBox.get("y") * this.scale,
        width: txtWidth + txtWidth,
        height: textBox.get("size") * this.scale
      };
      this.applyTransforms(textBox, bbox);
      return this.g2d.fillText(textBox.get("text"), bbox.x, bbox.y + bbox.height);
    };

    SlideDrawer.prototype.paintImage = function(imageModel) {
      return this._imageLoaded(imageModel.cachedImage, imageModel);
    };

    SlideDrawer.prototype._imageLoaded = function(image, imageModel) {
      var bbox;
      bbox = {
        x: imageModel.get("x") * this.scale,
        y: imageModel.get("y") * this.scale,
        width: image.naturalWidth * this.scale,
        height: image.naturalHeight * this.scale
      };
      this.applyTransforms(imageModel, bbox);
      return this.g2d.drawImage(image, bbox.x, bbox.y, bbox.width, bbox.height);
    };

    SlideDrawer.prototype.applyTransforms = function(component, bbox) {
      var rotation, scale, skewX, skewY, transform;
      rotation = component.get("rotate");
      this.g2d.translate(bbox.width / 2 + bbox.x, bbox.height / 2 + bbox.y);
      if (rotation != null) this.g2d.rotate(rotation);
      scale = component.get("scale");
      if (scale != null) this.g2d.scale(scale, scale);
      skewX = component.get("skewX");
      skewY = component.get("skewY");
      if (skewX || skewY) {
        transform = [1, 0, 0, 1, 0, 0];
        if (skewX) transform[2] = skewX;
        if (skewY) transform[1] = skewY;
        this.g2d.transform.apply(this.g2d, transform);
      }
      return this.g2d.translate(-1 * (bbox.width / 2 + bbox.x), -1 * (bbox.height / 2 + bbox.y));
    };

    SlideDrawer.prototype.paintTable = function() {};

    SlideDrawer.prototype.dispose = function() {
      return this.model.off(null, null, this);
    };

    return SlideDrawer;

  })();
});
