// Generated by CoffeeScript 1.3.3
/*
@author Tantaman
*/

var continuation;

requirejs.config({
  paths: {
    "css": "vendor/amd_plugins/css",
    "text": "vendor/amd_plugins/text"
  },
  shim: {
    'vendor/amd/jszip': {
      exports: 'JSZip'
    },
    'vendor/amd/jszip-deflate': ['vendor/amd/jszip'],
    'vendor/amd/jquery-1.7-matt': {
      exports: 'jQuery'
    },
    'vendor/amd/jqueryUI': ['vendor/amd/jquery-1.7-matt'],
    'vendor/amd/underscore': {
      exports: '_'
    },
    'vendor/amd/bootstrap': ['vendor/amd/jquery-1.7-matt'],
    'vendor/amd/bootstrapDropdown': ['vendor/amd/bootstrap', 'vendor/amd/jquery-1.7-matt'],
    '../res/jqplugins/colorpicker/js/colorpicker': ['vendor/amd/jquery-1.7-matt'],
    '../res/jqplugins/gradient_picker/jquery.gradientPicker': ['vendor/amd/jquery-1.7-matt'],
    'vendor/amd/backbone': {
      exports: 'Backbone',
      deps: ['vendor/amd/underscore', 'vendor/amd/jquery-1.7-matt']
    }
  }
});

if (!(window.localStorage != null)) {
  window.localStorage = {
    setItem: function() {},
    getItem: function() {},
    length: 0
  };
}

if (!(Function.bind != null) || (Function.prototype.bind != null)) {
  Function.prototype.bind = function(ctx) {
    var fn;
    fn = this;
    return function() {
      return fn.apply(ctx, arguments);
    };
  };
}

if (window.location.href.indexOf("preview=true") !== -1) {

} else {
  continuation = function() {
    return requirejs(["ui/editor/Editor", "model/presentation/Deck", "storage/FileStorage"], function(Editor, Deck, FileStorage) {
      var deck, editor, lastPres, pres;
      deck = new Deck();
      editor = new Editor({
        model: deck
      });
      window.zTracker = {
        z: 0,
        next: function() {
          return ++this.z;
        }
      };
      $("body").append(editor.render());
      lastPres = localStorage.getItem("StrutLastPres");
      if (lastPres != null) {
        pres = FileStorage.open(lastPres);
        if (pres != null) {
          deck["import"](pres);
        }
      }
      if (!(lastPres != null)) {
        return deck.newSlide();
      }
    });
  };
  requirejs(["vendor/amd/backbone", "state/DefaultState", "vendor/amd/jquery-1.7-matt", "vendor/amd/bootstrapDropdown", "vendor/amd/jqueryUI", "../res/jqplugins/colorpicker/js/colorpicker", "../res/jqplugins/gradient_picker/jquery.gradientPicker"], function(Backbone, DefaultState, jQuery) {
    var $;
    Backbone.sync = function(method, model, options) {
      if (options.keyTrail != null) {
        return options.success(DefaultState.get(options.keyTrail));
      }
    };
    window.slideConfig = {
      size: {
        width: 1024,
        height: 768
      }
    };
    jQuery.fn.selectText = function(){
		    var doc = document;
		    var element = this[0];
		    if (doc.body.createTextRange) {
		        var range = document.body.createTextRange();
		        range.moveToElementText(element);
		        range.select();
		    } else if (window.getSelection) {
		        var selection = window.getSelection();        
		        var range = document.createRange();
		        range.selectNodeContents(element);
		        selection.removeAllRanges();
		        selection.addRange(range);
		    }
		    return this;
		};;

    $ = jQuery;
    window.browserPrefix = "";
    if ($.browser.mozilla) {
      window.browserPrefix = "-moz-";
    } else if ($.browser.msie) {
      window.browserPrefix = "-ms-";
    } else if ($.browser.opera) {
      window.browserPrefix = "-o-";
    } else if ($.browser.webkit) {
      window.browserPrefix = "-webkit-";
    }
    return continuation();
  });
}
