// Generated by CoffeeScript 1.3.3

define(["storage/FileStorage"], function(FileStorage) {
  var AutoSaver, defaults;
  defaults = {
    interval: 10
  };
  return AutoSaver = (function() {

    function AutoSaver(deck, options) {
      this.deck = deck;
      this.options = options;
      this.options || (this.options = {});
      _.defaults(this.options, defaults);
    }

    AutoSaver.prototype.start = function() {
      var _this = this;
      if (!(this.handle != null)) {
        return this.handle = setInterval(function() {
          return _this._save();
        }, this.options.interval * 1000);
      }
    };

    AutoSaver.prototype.stop = function() {
      if (this.handle != null) {
        clearInterval(this.handle);
        return this.handle = null;
      }
    };

    AutoSaver.prototype._save = function() {
      var fileName;
      fileName = this.deck.get("fileName");
      if (!(fileName != null)) {
        return;
      }
      return FileStorage.save(fileName, this.deck.toJSON(false, true));
    };

    return AutoSaver;

  })();
});
