// Generated by CoffeeScript 1.3.3
/*
@author Matt Crinklaw-Vogt
*/

define(["common/Calcium"], function(Backbone) {
  return Backbone.Model.extend({
    initialize: function() {},
    constructor: function SpatialObject() {
			Backbone.Model.prototype.constructor.apply(this, arguments);
		}
  });
});
