// Generated by `rindle schema gen` from the daemon's introspected schema (GET /schema).
// Do not edit by hand — re-run the generator after each migration.
//
// Column kinds come from your declared SQL types: TEXT maps to string(), INTEGER/REAL to
// number(), and a column declared BOOLEAN/BOOL or JSON to boolean()/json(). Nullability comes from
// the SQL too: a nullable column is string().nullable() (typed T | null), a NOT NULL column is bare
// string(), and PK columns are always non-null. The only thing the SQL can't carry is a refinement
// *within* a kind — the element type of json<T>(), or a string/number literal union — declare those
// ONCE in a hand-written module with refineTable(...) + refineSchema(...); they survive every regen
// of this file.

import { createSchema, number, string, table } from "@rindle/client";

export const component = table("component")
  .columns({
    id: string(),
    slide_id: string().nullable(),
    type: string().nullable(),
    z_order: number().nullable(),
    x: number().nullable(),
    y: number().nullable(),
    scale_x: number().nullable(),
    scale_y: number().nullable(),
    scale_w: number().nullable(),
    scale_h: number().nullable(),
    rotate: number().nullable(),
    skew_x: number().nullable(),
    skew_y: number().nullable(),
    custom_classes: string().nullable(),
    fill: string().nullable(),
    props: string().nullable(),
  })
  .primaryKey("id");

export const custom_background = table("custom_background")
  .columns({
    id: string(),
    deck_id: string().nullable(),
    klass: string().nullable(),
    style: string().nullable(),
  })
  .primaryKey("id");

export const deck = table("deck")
  .columns({
    id: string(),
    title: string().nullable(),
    created: number().nullable(),
    modified: number().nullable(),
    background: string().nullable(),
    surface: string().nullable(),
    chosen_presenter: string().nullable(),
    canned_transition: string().nullable(),
    custom_stylesheet: string().nullable(),
    deck_version: string().nullable(),
    owner_id: string().nullable(),
    visibility: string().nullable(),
    share_token: string().nullable(),
    heading_font: string().nullable(),
    heading_color: string().nullable(),
    body_font: string().nullable(),
    body_color: string().nullable(),
    default_slide_mode: string().nullable(),
    text_align: string().nullable(),
  })
  .primaryKey("id");

export const deck_share = table("deck_share")
  .columns({
    id: string(),
    deck_id: string().nullable(),
    user_id: string().nullable(),
    role: string().nullable(),
    created: number().nullable(),
  })
  .primaryKey("id");

export const slide = table("slide")
  .columns({
    id: string(),
    deck_id: string().nullable(),
    sort: string().nullable(),
    x: number().nullable(),
    y: number().nullable(),
    z: number().nullable(),
    rotate_x: number().nullable(),
    rotate_y: number().nullable(),
    rotate_z: number().nullable(),
    imp_scale: number().nullable(),
    background: string().nullable(),
    surface: string().nullable(),
    created: number().nullable(),
    modified: number().nullable(),
    markdown: string().nullable(),
    render_mode: string().nullable(),
    text_align: string().nullable(),
    doc: string().nullable(),
  })
  .primaryKey("id");

export const user_profile = table("user_profile")
  .columns({
    id: string(),
    display_name: string().nullable(),
    updated: number().nullable(),
  })
  .primaryKey("id");

export const schema = createSchema({ tables: [component, custom_background, deck, deck_share, slide, user_profile] });
