// Generated by `rindle schema gen` from the daemon's introspected schema (GET /schema).
// Do not edit by hand — re-run the generator after each migration.
//
// Column kinds come from your declared SQL types: TEXT maps to string(), INTEGER/REAL to
// number(), and a column declared BOOLEAN/BOOL or JSON to boolean()/json(). Nullability comes from
// the SQL too: a nullable column is string().nullable() (typed T | null), a NOT NULL column is bare
// string(), and PK columns are always non-null. The only thing the SQL can't carry is a refinement
// *within* a kind — the element type of json<T>(), or a string/number literal union — declare those
// ONCE in a hand-written module with refineTable(...) + refineSchema(...); they survive every regen
// of this file.

import { createSchema, json, number, string, table } from "@rindle/client";

export const component = table("component")
  .columns({
    id: string(),
    slide_id: string(),
    type: string(),
    z_order: number(),
    x: number(),
    y: number(),
    scale_x: number(),
    scale_y: number(),
    scale_w: number(),
    scale_h: number(),
    rotate: number(),
    skew_x: number(),
    skew_y: number(),
    custom_classes: string(),
    fill: string(),
    props: json(),
  })
  .primaryKey("id");

export const custom_background = table("custom_background")
  .columns({
    id: string(),
    deck_id: string(),
    klass: string(),
    style: string(),
  })
  .primaryKey("id");

export const deck = table("deck")
  .columns({
    id: string(),
    title: string(),
    created: number(),
    modified: number(),
    background: string(),
    surface: string(),
    chosen_presenter: string(),
    canned_transition: string(),
    custom_stylesheet: string(),
    deck_version: string(),
    owner_id: string(),
    visibility: string(),
    share_token: string(),
    heading_font: string(),
    heading_color: string(),
    body_font: string(),
    body_color: string(),
    default_slide_mode: string(),
    text_align: string(),
  })
  .primaryKey("id");

export const deck_share = table("deck_share")
  .columns({
    id: string(),
    deck_id: string(),
    user_id: string(),
    role: string(),
    created: number(),
  })
  .primaryKey("id");

export const slide = table("slide")
  .columns({
    id: string(),
    deck_id: string(),
    sort: string(),
    x: number(),
    y: number(),
    z: number(),
    rotate_x: number(),
    rotate_y: number(),
    rotate_z: number(),
    imp_scale: number(),
    background: string(),
    surface: string(),
    created: number(),
    modified: number(),
    markdown: string(),
    render_mode: string(),
    text_align: string(),
    doc: string(),
  })
  .primaryKey("id");

export const user_profile = table("user_profile")
  .columns({
    id: string(),
    display_name: string(),
    updated: number(),
  })
  .primaryKey("id");

export const schema = createSchema({ tables: [component, custom_background, deck, deck_share, slide, user_profile] });
