// Generated by CoffeeScript 1.2.1-pre
/*
@author Matt Crinklaw-Vogt
*/

define(["vendor/backbone", "./TransitionSlideSnapshot", "../Templates", "./TransitionEditorButtonBarView", "model/editor/transition_editor/TransitionEditorButtonBarModel", "css!../res/css/TransitionEditor.css"], function(Backbone, TransitionSlideSnapshot, Templates, ButtonBarView, ButtonBarModel, empty) {
  return Backbone.View.extend({
    className: "transitionEditor",
    events: {
      "click": "clicked"
    },
    scale: window.slideConfig.size.width / 150,
    initialize: function() {
      var _this = this;
      this.name = "Transition Editor";
      this._snapshots = [];
      return $(window).resize(function() {
        return _this.resized();
      });
    },
    show: function() {
      this.hidden = false;
      this.$el.removeClass("disp-none");
      return this._partialRender();
    },
    resized: function() {
      return this.$el.css("height", window.innerHeight - 80);
    },
    hide: function() {
      this.hidden = true;
      this._disposeOldView();
      return this.$el.addClass("disp-none");
    },
    clicked: function() {
      return this.model.get("slides").forEach(function(slide) {
        if (slide.get("selected")) return slide.set("selected", false);
      });
    },
    _disposeOldView: function() {
      this._snapshots.forEach(function(snapshot) {
        return snapshot.remove();
      });
      return this._snapshots = [];
    },
    render: function() {
      this.$el.html(Templates.TransitionEditor());
      this.buttonBarView = new ButtonBarView({
        model: new ButtonBarModel({
          deck: this.model
        }),
        el: this.$el.find(".navbar")
      });
      this.buttonBarView.render();
      this._partialRender();
      this.resized();
      return this.$el;
    },
    _partialRender: function() {
      var $container, cnt, colCnt, slides,
        _this = this;
      this.buttonBarView.partialRender();
      $container = this.$el.find(".transitionSlides");
      $container.html("");
      slides = this.model.get("slides");
      colCnt = 6;
      cnt = 0;
      return slides.each(function(slide) {
        var snapshot, x;
        x = slide.get("x");
        if (!(x != null)) {
          slide.set("x", cnt * 160 + 30);
          slide.set("y", ((cnt / colCnt) | 0) * 160 + 80);
        }
        ++cnt;
        snapshot = new TransitionSlideSnapshot({
          model: slide
        });
        _this._snapshots.push(snapshot);
        return $container.append(snapshot.render());
      });
    }
  });
});
