// Generated by CoffeeScript 1.2.1-pre

define(["vendor/backbone"], function(Backbone) {
  var buttonBarOptions;
  buttonBarOptions = {
    rotateX: function(e) {},
    rotateY: function(e) {},
    rotateZ: function(e) {}
  };
  return Backbone.View.extend({
    events: function() {
      return {
        "keypress *[data-option]": "optionChosen",
        "paste *[data-option]": "optionChosen"
      };
    }
  });
});
