// Generated by CoffeeScript 1.2.1-pre

define(["vendor/backbone", "./Binder"], function(Backbone, Binder) {
  return Backbone.View.extend({
    initialize: function() {
      return this._binder = new Binder({
        model: this.model,
        el: this.$el,
        mapping: this.mapping
      });
    }
  });
});
