// Generated by CoffeeScript 1.2.1-pre
/*
@author Matt Crinklaw-Vogt
*/

define(["./ImageView", "./TableView", "./TextBoxView"], function(ImageView, TableView, TextBoxView) {
  var ComponentViewFactory;
  return ComponentViewFactory = {
    createView: function(model) {
      var type;
      type = model.constructor.name;
      switch (type) {
        case "TextBox":
          return new TextBoxView({
            model: model
          });
        case "Image":
          return new ImageView({
            model: model
          });
        case "Table":
          return new TableView({
            model: model
          });
      }
    }
  };
});
