// Generated by CoffeeScript 1.3.3
/*
@author Matt Crinklaw-Vogt
*/

define(["common/MapResolver"], function(MapResolver) {
  var iface, stateMap;
  stateMap = {
    editor: {
      slideEditor: {
        buttonBar: {
          fontSize: 72,
          fontFamily: "'Lato', sans-serif",
          fontColor: "grey",
          fontStyle: "",
          fontWeight: ""
        }
      }
    }
  };
  return iface = {
    get: function(key) {
      return MapResolver.resolveItem(stateMap, key);
    }
  };
});
