// Generated by CoffeeScript 1.3.3

define(function() {
  var FileUtils;
  return FileUtils = {
    baseName: function(path, extension) {
      var idx;
      if (path[path.length - 1] === "/") {
        path = path.substring(0, path.length - 1);
      }
      idx = path.lastIndexOf("/");
      if (idx !== -1 && idx + 1 < path.length) {
        path = path.substring(idx + 1, path.length);
      }
      if (extension != null) {
        idx = path.lastIndexOf(extension);
        if (idx + extension.length === path.length) {
          path = path.substring(0, idx);
        }
      }
      return path;
    }
  };
});
