// Generated by CoffeeScript 1.3.3

define({
  round: function(num, dec) {
    var factor;
    (dec != null) || (dec = 0);
    factor = Math.pow(10, dec);
    return Math.round(num * factor) / factor;
  },
  toDeg: function(rads) {
    return rads * 180 / Math.PI;
  },
  toRads: function(deg) {
    return deg * Math.PI / 180;
  },
  compare: function(v1, v2, thresh) {
    return Math.abs(v1 - v2) < thresh;
  }
});
