// Generated by CoffeeScript 1.2.1-pre

define({
  round: function(num, dec) {
    var factor;
    (dec != null) || (dec = 0);
    factor = Math.pow(10, dec);
    return Math.round(num * factor) / factor;
  }
});
