/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareDeckIdRouteImport } from './routes/share.$deckId'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as ApiImageSearchRouteImport } from './routes/api.image-search'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiGenerateRouteImport } from './routes/api.generate'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiArtifactRouteImport } from './routes/api.artifact'
import { Route as ApiArrangeRouteImport } from './routes/api.arrange'
import { Route as AKeyRouteImport } from './routes/a.$key'
import { Route as DeckDeckIdPlayRouteImport } from './routes/deck.$deckId_.play'
import { Route as ApiRindleUploadRouteImport } from './routes/api.rindle.upload'
import { Route as ApiRindleReadRouteImport } from './routes/api.rindle.read'
import { Route as ApiRindleQueryRouteImport } from './routes/api.rindle.query'
import { Route as ApiRindleMutateRouteImport } from './routes/api.rindle.mutate'
import { Route as ApiRindleConfigRouteImport } from './routes/api.rindle.config'
import { Route as ApiModelStatusRouteImport } from './routes/api.model.status'
import { Route as ApiModelDisconnectRouteImport } from './routes/api.model.disconnect'
import { Route as ApiModelConnectRouteImport } from './routes/api.model.connect'
import { Route as ApiChatActRouteImport } from './routes/api.chat.act'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiRindleUploadsKeyRouteImport } from './routes/api.rindle.uploads.$key'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareDeckIdRoute = ShareDeckIdRouteImport.update({
  id: '/share/$deckId',
  path: '/share/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageSearchRoute = ApiImageSearchRouteImport.update({
  id: '/api/image-search',
  path: '/api/image-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactRoute = ApiArtifactRouteImport.update({
  id: '/api/artifact',
  path: '/api/artifact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArrangeRoute = ApiArrangeRouteImport.update({
  id: '/api/arrange',
  path: '/api/arrange',
  getParentRoute: () => rootRouteImport,
} as any)
const AKeyRoute = AKeyRouteImport.update({
  id: '/a/$key',
  path: '/a/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdPlayRoute = DeckDeckIdPlayRouteImport.update({
  id: '/deck/$deckId_/play',
  path: '/deck/$deckId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleUploadRoute = ApiRindleUploadRouteImport.update({
  id: '/api/rindle/upload',
  path: '/api/rindle/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleReadRoute = ApiRindleReadRouteImport.update({
  id: '/api/rindle/read',
  path: '/api/rindle/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleQueryRoute = ApiRindleQueryRouteImport.update({
  id: '/api/rindle/query',
  path: '/api/rindle/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleMutateRoute = ApiRindleMutateRouteImport.update({
  id: '/api/rindle/mutate',
  path: '/api/rindle/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleConfigRoute = ApiRindleConfigRouteImport.update({
  id: '/api/rindle/config',
  path: '/api/rindle/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelStatusRoute = ApiModelStatusRouteImport.update({
  id: '/api/model/status',
  path: '/api/model/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelDisconnectRoute = ApiModelDisconnectRouteImport.update({
  id: '/api/model/disconnect',
  path: '/api/model/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelConnectRoute = ApiModelConnectRouteImport.update({
  id: '/api/model/connect',
  path: '/api/model/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatActRoute = ApiChatActRouteImport.update({
  id: '/act',
  path: '/act',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleUploadsKeyRoute = ApiRindleUploadsKeyRouteImport.update({
  id: '/api/rindle/uploads/$key',
  path: '/api/rindle/uploads/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/a/$key': typeof AKeyRoute
  '/api/arrange': typeof ApiArrangeRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/generate': typeof ApiGenerateRoute
  '/api/image': typeof ApiImageRoute
  '/api/image-search': typeof ApiImageSearchRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/share/$deckId': typeof ShareDeckIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/act': typeof ApiChatActRoute
  '/api/model/connect': typeof ApiModelConnectRoute
  '/api/model/disconnect': typeof ApiModelDisconnectRoute
  '/api/model/status': typeof ApiModelStatusRoute
  '/api/rindle/config': typeof ApiRindleConfigRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
  '/api/rindle/upload': typeof ApiRindleUploadRoute
  '/deck/$deckId/play': typeof DeckDeckIdPlayRoute
  '/api/rindle/uploads/$key': typeof ApiRindleUploadsKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/a/$key': typeof AKeyRoute
  '/api/arrange': typeof ApiArrangeRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/generate': typeof ApiGenerateRoute
  '/api/image': typeof ApiImageRoute
  '/api/image-search': typeof ApiImageSearchRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/share/$deckId': typeof ShareDeckIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/act': typeof ApiChatActRoute
  '/api/model/connect': typeof ApiModelConnectRoute
  '/api/model/disconnect': typeof ApiModelDisconnectRoute
  '/api/model/status': typeof ApiModelStatusRoute
  '/api/rindle/config': typeof ApiRindleConfigRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
  '/api/rindle/upload': typeof ApiRindleUploadRoute
  '/deck/$deckId/play': typeof DeckDeckIdPlayRoute
  '/api/rindle/uploads/$key': typeof ApiRindleUploadsKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/a/$key': typeof AKeyRoute
  '/api/arrange': typeof ApiArrangeRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/generate': typeof ApiGenerateRoute
  '/api/image': typeof ApiImageRoute
  '/api/image-search': typeof ApiImageSearchRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/share/$deckId': typeof ShareDeckIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/act': typeof ApiChatActRoute
  '/api/model/connect': typeof ApiModelConnectRoute
  '/api/model/disconnect': typeof ApiModelDisconnectRoute
  '/api/model/status': typeof ApiModelStatusRoute
  '/api/rindle/config': typeof ApiRindleConfigRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
  '/api/rindle/upload': typeof ApiRindleUploadRoute
  '/deck/$deckId_/play': typeof DeckDeckIdPlayRoute
  '/api/rindle/uploads/$key': typeof ApiRindleUploadsKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/a/$key'
    | '/api/arrange'
    | '/api/artifact'
    | '/api/chat'
    | '/api/generate'
    | '/api/image'
    | '/api/image-search'
    | '/deck/$deckId'
    | '/share/$deckId'
    | '/api/auth/$'
    | '/api/chat/act'
    | '/api/model/connect'
    | '/api/model/disconnect'
    | '/api/model/status'
    | '/api/rindle/config'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
    | '/api/rindle/upload'
    | '/deck/$deckId/play'
    | '/api/rindle/uploads/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/a/$key'
    | '/api/arrange'
    | '/api/artifact'
    | '/api/chat'
    | '/api/generate'
    | '/api/image'
    | '/api/image-search'
    | '/deck/$deckId'
    | '/share/$deckId'
    | '/api/auth/$'
    | '/api/chat/act'
    | '/api/model/connect'
    | '/api/model/disconnect'
    | '/api/model/status'
    | '/api/rindle/config'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
    | '/api/rindle/upload'
    | '/deck/$deckId/play'
    | '/api/rindle/uploads/$key'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/a/$key'
    | '/api/arrange'
    | '/api/artifact'
    | '/api/chat'
    | '/api/generate'
    | '/api/image'
    | '/api/image-search'
    | '/deck/$deckId'
    | '/share/$deckId'
    | '/api/auth/$'
    | '/api/chat/act'
    | '/api/model/connect'
    | '/api/model/disconnect'
    | '/api/model/status'
    | '/api/rindle/config'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
    | '/api/rindle/upload'
    | '/deck/$deckId_/play'
    | '/api/rindle/uploads/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  AKeyRoute: typeof AKeyRoute
  ApiArrangeRoute: typeof ApiArrangeRoute
  ApiArtifactRoute: typeof ApiArtifactRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiImageSearchRoute: typeof ApiImageSearchRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  ShareDeckIdRoute: typeof ShareDeckIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiModelConnectRoute: typeof ApiModelConnectRoute
  ApiModelDisconnectRoute: typeof ApiModelDisconnectRoute
  ApiModelStatusRoute: typeof ApiModelStatusRoute
  ApiRindleConfigRoute: typeof ApiRindleConfigRoute
  ApiRindleMutateRoute: typeof ApiRindleMutateRoute
  ApiRindleQueryRoute: typeof ApiRindleQueryRoute
  ApiRindleReadRoute: typeof ApiRindleReadRoute
  ApiRindleUploadRoute: typeof ApiRindleUploadRoute
  DeckDeckIdPlayRoute: typeof DeckDeckIdPlayRoute
  ApiRindleUploadsKeyRoute: typeof ApiRindleUploadsKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$deckId': {
      id: '/share/$deckId'
      path: '/share/$deckId'
      fullPath: '/share/$deckId'
      preLoaderRoute: typeof ShareDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-search': {
      id: '/api/image-search'
      path: '/api/image-search'
      fullPath: '/api/image-search'
      preLoaderRoute: typeof ApiImageSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifact': {
      id: '/api/artifact'
      path: '/api/artifact'
      fullPath: '/api/artifact'
      preLoaderRoute: typeof ApiArtifactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arrange': {
      id: '/api/arrange'
      path: '/api/arrange'
      fullPath: '/api/arrange'
      preLoaderRoute: typeof ApiArrangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$key': {
      id: '/a/$key'
      path: '/a/$key'
      fullPath: '/a/$key'
      preLoaderRoute: typeof AKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId_/play': {
      id: '/deck/$deckId_/play'
      path: '/deck/$deckId/play'
      fullPath: '/deck/$deckId/play'
      preLoaderRoute: typeof DeckDeckIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/upload': {
      id: '/api/rindle/upload'
      path: '/api/rindle/upload'
      fullPath: '/api/rindle/upload'
      preLoaderRoute: typeof ApiRindleUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/read': {
      id: '/api/rindle/read'
      path: '/api/rindle/read'
      fullPath: '/api/rindle/read'
      preLoaderRoute: typeof ApiRindleReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/query': {
      id: '/api/rindle/query'
      path: '/api/rindle/query'
      fullPath: '/api/rindle/query'
      preLoaderRoute: typeof ApiRindleQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/mutate': {
      id: '/api/rindle/mutate'
      path: '/api/rindle/mutate'
      fullPath: '/api/rindle/mutate'
      preLoaderRoute: typeof ApiRindleMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/config': {
      id: '/api/rindle/config'
      path: '/api/rindle/config'
      fullPath: '/api/rindle/config'
      preLoaderRoute: typeof ApiRindleConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/status': {
      id: '/api/model/status'
      path: '/api/model/status'
      fullPath: '/api/model/status'
      preLoaderRoute: typeof ApiModelStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/disconnect': {
      id: '/api/model/disconnect'
      path: '/api/model/disconnect'
      fullPath: '/api/model/disconnect'
      preLoaderRoute: typeof ApiModelDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/connect': {
      id: '/api/model/connect'
      path: '/api/model/connect'
      fullPath: '/api/model/connect'
      preLoaderRoute: typeof ApiModelConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/act': {
      id: '/api/chat/act'
      path: '/act'
      fullPath: '/api/chat/act'
      preLoaderRoute: typeof ApiChatActRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/uploads/$key': {
      id: '/api/rindle/uploads/$key'
      path: '/api/rindle/uploads/$key'
      fullPath: '/api/rindle/uploads/$key'
      preLoaderRoute: typeof ApiRindleUploadsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiChatRouteChildren {
  ApiChatActRoute: typeof ApiChatActRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatActRoute: ApiChatActRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  AKeyRoute: AKeyRoute,
  ApiArrangeRoute: ApiArrangeRoute,
  ApiArtifactRoute: ApiArtifactRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiImageRoute: ApiImageRoute,
  ApiImageSearchRoute: ApiImageSearchRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  ShareDeckIdRoute: ShareDeckIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiModelConnectRoute: ApiModelConnectRoute,
  ApiModelDisconnectRoute: ApiModelDisconnectRoute,
  ApiModelStatusRoute: ApiModelStatusRoute,
  ApiRindleConfigRoute: ApiRindleConfigRoute,
  ApiRindleMutateRoute: ApiRindleMutateRoute,
  ApiRindleQueryRoute: ApiRindleQueryRoute,
  ApiRindleReadRoute: ApiRindleReadRoute,
  ApiRindleUploadRoute: ApiRindleUploadRoute,
  DeckDeckIdPlayRoute: DeckDeckIdPlayRoute,
  ApiRindleUploadsKeyRoute: ApiRindleUploadsKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
