/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareDeckIdRouteImport } from './routes/share.$deckId'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as DeckDeckIdPlayRouteImport } from './routes/deck.$deckId_.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareDeckIdRoute = ShareDeckIdRouteImport.update({
  id: '/share/$deckId',
  path: '/share/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdPlayRoute = DeckDeckIdPlayRouteImport.update({
  id: '/deck/$deckId_/play',
  path: '/deck/$deckId/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/share/$deckId': typeof ShareDeckIdRoute
  '/deck/$deckId/play': typeof DeckDeckIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/share/$deckId': typeof ShareDeckIdRoute
  '/deck/$deckId/play': typeof DeckDeckIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/share/$deckId': typeof ShareDeckIdRoute
  '/deck/$deckId_/play': typeof DeckDeckIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck/$deckId' | '/share/$deckId' | '/deck/$deckId/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck/$deckId' | '/share/$deckId' | '/deck/$deckId/play'
  id:
    | '__root__'
    | '/'
    | '/deck/$deckId'
    | '/share/$deckId'
    | '/deck/$deckId_/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  ShareDeckIdRoute: typeof ShareDeckIdRoute
  DeckDeckIdPlayRoute: typeof DeckDeckIdPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$deckId': {
      id: '/share/$deckId'
      path: '/share/$deckId'
      fullPath: '/share/$deckId'
      preLoaderRoute: typeof ShareDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId_/play': {
      id: '/deck/$deckId_/play'
      path: '/deck/$deckId/play'
      fullPath: '/deck/$deckId/play'
      preLoaderRoute: typeof DeckDeckIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  ShareDeckIdRoute: ShareDeckIdRoute,
  DeckDeckIdPlayRoute: DeckDeckIdPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
