// Generated by CoffeeScript 1.3.3

define(["vendor/amd/jszip"], function(JSZip) {
  var Archiver, defaults;
  defaults = {
    includeImages: false,
    includeFonts: true
  };
  return Archiver = {
    createArchive: function(presentation, options) {
      var archive, presentationCopy;
      options || (options = {});
      _.defaults(options, defaults);
      archive = new JSZip();
      presentationCopy = new Deck();
      return presentationCopy["import"](presentation.toJSON(false, true));
    }
  };
  /*
  		var zip = new JSZip();
  		zip.file("Hello.txt", "Hello World\n");
  		var img = zip.folder("images");
  		img.file("smile.gif", imgData, {base64: true});
  		var content = zip.generate();
  		location.href="data:application/zip;base64,"+content;
  */

});
