// Generated by CoffeeScript 1.3.3

define(["vendor/amd/jszip"], function(JSZip) {
  var Archiver, defaults;
  defaults = {
    includeImages: false,
    includeFonts: true
  };
  return Archiver = {
    createArchive: function(presentation, options) {
      var archive, presentationCopy, showStr,
        _this = this;
      options || (options = {});
      _.defaults(options, defaults);
      archive = new JSZip();
      presentationCopy = new Deck();
      presentationCopy["import"](presentation.toJSON(false, true));
      presentationCopy.get("slides").each(function(slide) {
        return _this.processComponents(slide.get("components"), archive, options);
      });
      return showStr = "<!doctype html><html>" + ImpressRenderer.render(this.model.attributes) + "</html>";
    },
    processComponents: function(components, archive, options) {
      var _this = this;
      return components.forEach(function(component) {
        return _this.processComponent(component, archive, options);
      });
    },
    processComponent: function(component, archive, options) {}
  };
  /*
  		var zip = new JSZip();
  		zip.file("Hello.txt", "Hello World\n");
  		var img = zip.folder("images");
  		img.file("smile.gif", imgData, {base64: true});
  		var content = zip.generate();
  		location.href="data:application/zip;base64,"+content;
  */

});
